stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests=false"
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/paypilot"
  FRONTEND_DIR: "frontend"
  BACKEND_DIR: "backend"

# ----------------------------
# Build Frontend
# ----------------------------
build-frontend:
  stage: build
  image: node:20
  script:
    - echo "Installing frontend dependencies..."
    - cd $FRONTEND_DIR
    - npm install
    - echo "Building frontend..."
    - npm run build
  artifacts:
    paths:
      - $FRONTEND_DIR/build
    expire_in: 1 hour

# ----------------------------
# Build Backend
# ----------------------------
build-backend:
  stage: build
  image: maven:3.9.2-openjdk-17
  script:
    - echo "Building backend with Maven..."
    - cd $BACKEND_DIR
    - mvn clean package $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - $BACKEND_DIR/target/*.jar
    expire_in: 1 hour
  dependencies:
    - build-frontend

# ----------------------------
# Run Backend Tests
# ----------------------------
test-backend:
  stage: test
  image: maven:3.9.2-openjdk-17
  script:
    - echo "Running backend tests..."
    - cd $BACKEND_DIR
    - mvn test
  dependencies:
    - build-backend

# ----------------------------
# Build and Push Docker Image
# ----------------------------
deploy:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Logging in to GitLab Container Registry..."
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE .
    - echo "Pushing Docker image..."
    - docker push $DOCKER_IMAGE
    - echo "Docker image pushed successfully!"
  only:
    - main
