-- Users
CREATE TABLE users (
   id NUMBER PRIMARY KEY,
   email VARCHAR2(100) UNIQUE NOT NULL,
   password VARCHAR2(100) NOT NULL,
   name VARCHAR2(100)
);

-- Bills
CREATE TABLE bills (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    title VARCHAR2(100),
    amount NUMBER,
    due_date DATE,
    category VARCHAR2(50),
    status VARCHAR2(20),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Payments
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    bill_id NUMBER,
    amount_paid NUMBER,
    payment_date DATE,
    method VARCHAR2(50),
    FOREIGN KEY (bill_id) REFERENCES bills(id)
);

-- Reminder Settings
CREATE TABLE reminder_settings (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id NUMBER,
    frequency VARCHAR2(20),
    days_before_due NUMBER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);
